version: '3'
services:
  rasa:
    image: rasa/rasa:latest-full
    ports:
      - "5005:5005"
    volumes:
      - ./rasa:/app
    command: >
      run --enable-api --cors "*"
  
  keycloak:
    image: jboss/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

  node_red:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - ./node_red_data:/data

  nodejs:
    build: ./node_server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
